# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TerraformStateMover < Formula
  desc "Refactoring Terraform code has never been easier"
  homepage "https://github.com/mbode/terraform-state-mover"
  version "0.4.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mbode/terraform-state-mover/releases/download/0.4.0/terraform-state-mover_0.4.0_Darwin_x86_64.tar.gz"
      sha256 "92e3da0b358933afdec8a48396ef0611c65bac70e418b42563cb7955a9a6a4d9"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mbode/terraform-state-mover/releases/download/0.4.0/terraform-state-mover_0.4.0_Linux_x86_64.tar.gz"
      sha256 "b2cde5b52680edca47b2fdb4a95752c455167eccda7f82654b8730bb7400f869"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mbode/terraform-state-mover/releases/download/0.4.0/terraform-state-mover_0.4.0_Linux_arm64.tar.gz"
      sha256 "d8aa5090c317947f89dcf58069c3ff8f5e6fe6ac921d8bf633372be7e70fbd48"
    end
  end

  def install
    bin.install "terraform-state-mover"
  end

  test do
    system "#{bin}/terraform-state-mover --version"
  end
end
