# This file was generated by GoReleaser. DO NOT EDIT.
class TerraformStateMover < Formula
  desc "Refactoring Terraform code has never been easier"
  homepage "https://github.com/mbode/terraform-state-mover"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mbode/terraform-state-mover/releases/download/0.2.0/terraform-state-mover_0.2.0_Darwin_x86_64.tar.gz"
    sha256 "15b7f67094e073816e2e4e3955f79bd5babc7afb00b22243f551aaaf6a2a3f5e"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/mbode/terraform-state-mover/releases/download/0.2.0/terraform-state-mover_0.2.0_Linux_x86_64.tar.gz"
      sha256 "94109ea124b1bf8eaa00fd58d498f2f9600705a5572d6b44e10afe9df922fb9c"
    end
  end

  def install
    bin.install "terraform-state-mover"
  end

  test do
    system "#{bin}/terraform-state-mover --version"
  end
end
